name 'meanbox'
maintainer 'davideugenepratt'
maintainer_email 'david@davideugenepratt.com'
license 'Apache-2.0'
description 'Installs/Configures mexn stack components'
long_description 'Installs/Configures mexn stack components'
version '0.0.1'
chef_version '>= 12.1' if respond_to?(:chef_version)
supports 'ubuntu'
issues_url 'https://github.com/davideugenepratt/meanbox/issues'
source_url 'https://github.com/davideugenepratt/meanbox'
